### ISSUE TITLE
How to compose expression to compare property with enum value?

### ISSUE THREAD

**Issue by arteny** [Alex141/CalcBinding#12]
I didn't find a way how to bind visibility with enum compare condition:
`<WrapPanel Margin="5" Visibility="{c:Binding 'MyProperty==Value1'}">`
Instead of Value1 I tried also MyEnumType.Value1, local:MyEnumType.Value1, nothing helps, everything result is 'Visible' with error:
System.Windows.Data Warning: 40 : BindingExpression path error: 'Value1' property not found on 'object' ''TabModel' (HashCode=42904806)'. BindingExpression:Path=local; DataItem='TabModel' (HashCode=42904806); target element is 'WrapPanel' (Name=''); target property is 'Visibility' (type 'Visibility')

**Comment by Alex141** [comment]
Good morning, Alexey! Thank you for your issue. 

The problem is that by default, any word other than numbers , string constants, or class math is considered as property of a view model. In the future it would be nice to make support for enum and other classes. As long as, you can give each enum value number and use it instead it name in xaml

**Comment by arteny** [comment]
When I use number associated to enum, it is also doesn't work, Error returned:
Binding error: calc converter can't convert expression{0}==0: Двоичный оператор Equal не определен для типов "bfsys.Status" и "System.Int32".

**Comment by Alex141** [comment]
Try to 
(int)yourProperty == 0

**Comment by arteny** [comment]
Again error:
Binding error: one of source fields is Unset, return null
System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='<null>' MultiBindingExpression:target element is 'WrapPanel' (Name=''); target property is 'IsEnabled' (type 'Boolean')

The code was:
```<WrapPanel Margin="5" IsEnabled="{c:Binding '(int)Status == 0'}">```

Anyway, workaround is not urgent for me already (so, you can close this ticket). If you can implement in future comparing with direct enum value - it will be great.

**Comment by Alex141** [comment]
Sorry, yes, I have taken note your issue, it is really very interested, and I will try to come up with it in near feature

**Comment by Alex141** [comment]
Enums are supported in version 2.3.0.0, nuget package will be available in nuget after indexing
