### ISSUE TITLE
Resharper compatibility

### ISSUE THREAD

**Issue by arteny** [Alex141/CalcBinding#13]
Such 'complex' property access shown as error in Resharper:
```<Setter Property="IsEnabled" Value="{c:Binding !DataContext.IsRemoved}"/>```
! pointed as not expected token.
And I can not ignore this line something like
```<!-- ReSharper disable Xaml.BindingWithContextNotResolved -->```
Only was is Disable Resharper Daemon for all file, but i don't like it much.

Is there some workaround?

**Comment by Alex141** [comment]
Hi, arteny!

I'm surprised for such problem with resharper. Some workaround for this doesn't exists yet, but I think it will be possible to add for operator '!' alias 'not' like it was made for '&&' and '||' operators. In principle, it is quick to do and write tests. In the near future I will do it. 

So, for examle, your xaml code will be:

```<Setter Property="IsEnabled" Value="{c:Binding not DataContext.IsRemoved}"/>```

Just do not forget to comment on the issues you have already created

**Comment by arteny** [comment]
Thank you for kind support!
Yes, I saw those issues have updates and will check them ASAP.



   Ñ óâàæåíèåì,
Àëåêñåé Áàðêàëîâ



   Best regards,  
   Alexey Barkalov




Date: Thu, 2 Apr 2015 08:41:15 -0700

**Comment by Alex141** [comment]
version 2.2.3.0 with that feature is released

**Comment by arteny** [comment]
It doesn't solve this issue. If change ! for not, Resharper error message changed to:
No constructor with 2 parameters found

**Comment by arteny** [comment]
And it is not related "complex" field, but anyway:
			<Setter Property="ShowCloseButton" Value="{c:Binding !IsAddButton}" />
or
			<Setter Property="ShowCloseButton" Value="{c:Binding not IsAddButton}" />

**Comment by Alex141** [comment]
Arteny, unfortunately I don't use Resharper, so as I undestand from your issue description, Resharper doesn't like special symbol '!' and that is the reason of error. Therefore I have added operator 'not' in a hope that resharper will not show error.

As I know resharper can't affect on compilation process, so even if you have that "resharper error" you can still compile and launch your project. Can you just turn off messages about these kinds of errors in resharper options?

If you other good solutions, please write about it.

**Comment by arteny** [comment]
Seems I found workaround, it is necessary to include path to single quotes like

     <Setter Property="ShowCloseButton" Value="{c:Binding '!IsAddButton'}" />

**Comment by Alex141** [comment]
And resharper don't show error?

**Comment by arteny** [comment]
yes, it is
