### ISSUE TITLE
Does not work with read-only propeties

### ISSUE THREAD

**Issue by xmedeko** [Alex141/CalcBinding#15]
I have a read-only property

    public bool IsEmpty  { get { ... } };

    <TextBlock Visibility="{cb:Binding IsEmpty}" />

But the CalcBinding fails with `TwoWay or OneWayToSource binding cannot work on the read-only property 'IsEmpty'`.

When I add `set` to my property (doing nothing), then it works OK.

**Comment by Alex141** [comment]
Hello, xmedeko!

Both of modes TwoWay and OneWayToSource need write access to source property, 'cause its update source property when target dependency property changes. So, exception you get is right:

https://msdn.microsoft.com/en-us/library/system.windows.data.bindingmode%28v=vs.110%29.aspx

So, with properties that haven't set method you need to use <b>OneWay</b> BindingMode

With regardes,
Alexandr

**Comment by xmedeko** [comment]
You are right, if I specify

    <TextBlock Visibility="{cb:Binding IsEmpty, Mode=Default}" />

then it works. But I think it's not good to explicitly write `Mode=Default`. Standard WPF binding do not need it.

**Comment by xmedeko** [comment]
Solved by #41 :-)

**Comment by Alex141** [comment]
xmedeko, yes, thank you) I'm sorry, I didn't understand you in the past year)
