### ISSUE TITLE
Add NotNullToVisibility

### ISSUE THREAD

**Issue by sm-g** [Alex141/CalcBinding#16]
Add `NotNullToVisibility` behaviour so we can write just

```
<Button Visibility="{calc:Binding SelectedItem, Mode=OneWay}" />
```

**Comment by Alex141** [comment]
Thank you for issue!

I will think about soon

**Comment by arteny** [comment]
I can't bind checking with null. It doesn't work:

    Visibility="{c:Binding 'IsSelected!=null'}"

result is visible for null.
Is it same issue? Then waiting for solution.
Thanks.

**Comment by Alex141** [comment]
Yes, it is really complex problem with support of properties that are 'null' when binding is initialized. Problem is that we can't determine type of source property if it is null, therefore can't build binding expression with that property and provide result to target property. Only if property change value from null to some not null object then we can build expression from binding path, calculate it and return right value to target property.

I continue working on this problem, but now there is only one 100% working workaround: not to use null properties and comparison with null

**Comment by Alex141** [comment]
Ok, I found solution, calcbinding support null values, so

sm-g, Arteny you can write as Arteny offered:

Visibility="{c:Binding 'IsSelected!=null'}"

<Button Visibility="{calc:Binding 'SelectedItem!=null' }" />
