### ISSUE TITLE
Ternary expression with color 

### ISSUE THREAD

**Issue by titouancreach** [Alex141/CalcBinding#17]
As the same as 

``` xaml
<TextBlock Text="{c:Binding '(1 == 2) ? 10 : 20'}" />
```

We may expect that

``` xaml
<TextBlock Text="Test" Foreground="{c:Binding '(1 == 1) ? #ff0000 : #000000'}" VerticalAlignment="Center"/>
```

display text in red.
Unfortanutelly, no text is displayed

Thank you :)

**Comment by Alex141** [comment]
Now you can write something like:


`<Button Background="{c:Binding '(A > B ? media:Brushes.LightBlue : media:Brushes.White)'}"/>`

where 'media' is defined as:

`xmlns:media ="clr-namespace:System.Windows.Media;assembly=PresentationCore"`

in header of xaml, see [documentation] (https://github.com/Alex141/CalcBinding#2-static-properties)
