### ISSUE TITLE
Different types multibing

### ISSUE THREAD

**Issue by arteny** [Alex141/CalcBinding#18]
Is it possible to use multibinding for different types of arguments?:

```
Content="{c:Binding Path='\'Points: \' + Points'}" 
```

where Points is int property.
It returns me error like:
Binding error: calc converter can't convert expression"Points"+{0}: Expression of type 'System.Int32' cannot be used for parameter of type 'System.Object' of method 'System.String Concat(System.Object, System.Object)'

WPF binding engine only takes the StringFormat property into account when the target property is of the String type. For properties of the Object type (like the BarStaticItem.Content property), the StringFormat property is ignored.
For instance this behavior in the standard Label control:

```
<Label Content="{Binding SomeProperty, StringFormat=This string will not be displayed}" />
```

Why I am looking may be there is some solution with your library.
Thanks.

**Comment by Alex141** [comment]
Hi, arteny!

Thank you for detailed description of issue. Unfortunately currently there is no workaround for this problem, because calcBinding repeats standart binding behavior in all ways besides binding expression
