### ISSUE TITLE
Use for TemplateBinding

### ISSUE THREAD

**Issue by xmedeko** [Alex141/CalcBinding#20]
I would like to use CalcBinding for `TemplateBinding` in `Style` definitrion, too. If it is already possible, add example to the `README.md`, thanks.
(Maybe using some kind of `{TemplateBinding Separator, Converter=cb:CalcConverter ...}`?)

**Comment by Alex141** [comment]
Thank you, excellent issue! Calcbinding doesn't support templateBinding yet, so I will think about it.

According to msdn "Using a TemplateBinding is equivalent to using a Binding with the RelativeSource property set to RelativeSource.TemplatedParent."
So you can write something like that:
{c:Binding Separator, RelativeSource={RelativeSource TemplatedParent}} 
as temporary workaround

Let me know if this way solved your problem!

 I think support of TemplateBinding will be very important improvement, thank you again!

**Comment by xmedeko** [comment]
Yep,

    {c:Binding Separator, RelativeSource={RelativeSource TemplatedParent}} 

works fine. Maybe just write it to `README.md`. Thanks.

**Comment by Alex141** [comment]
Well done, readme updated
