### ISSUE TITLE
DataTemplate bind to the whole item

### ISSUE THREAD

**Issue by xmedeko** [Alex141/CalcBinding#27]
I have a `<ListBox>` with `<DataTemplate>` and I need to bind `Visibility` to the condition, if the item is null or not. In a bare WPF I use

```
<TextBlock Text="Item is null" Visibility="{Binding Converter={StaticResource IsNullConverter}}" />
```

However, I would like to use a fancy CalcBinding, something like

```
<TextBlock Text="Item is null" Visibility="{cb:Binding '. == null'" />
```

How to denote the whole item in the expression (`.` is not working).

**Comment by Alex141** [comment]
As workaround I can offer this:

<TextBlock Text="Item is null" Visibility="{cb:Binding Path='DataContext == null', RelativeSource={RelativeSource Self}}" />
