### ISSUE TITLE
Support for MultiValue converter

### ISSUE THREAD

**Issue by xmedeko** [Alex141/CalcBinding#28]
I would like to use my custom converter inside the CalcBinding. A reason is that WPF Binding automatically listen to the `PropertyChanged` events, so I do not need to create a view model with the event subscribe and unsubscribe.

My idea is something like

```
<MultiBinding Converter="{cb:MultiBinding P0 and P1}" >
    <Binding Path="IsSomething"/>
    <Binding Path="MyEnumProperty" Converter="{StaticResource MyEnumToBoolConverter}"/>
</MultiBinding>
```

Or maybe `P[0] and P[1]` instead of `P0 and P1`.

**Comment by Alex141** [comment]
good enough idea)

XMedeko, I also saw your previous post, but I just wan't to say that now I really haven't time to develop new functionality in the library. Probably in January, I will be able to do this.

**Comment by hhonly** [comment]
@Alex141   I would like to see CalcBinding doing multibinding with properties of several different objects (sources) . Is CalcBinding capable of that now and if it is , can you show an example of doing that? thanks.

**Comment by Alex141** [comment]
@hhonly only binding to static properties of different classes and enums.
@xmedekom I don't think that this solution should be realized by calcBinding, because it is same approach as in QuickConveter library. Simply use that library for such complex expressions:
https://quickconverter.codeplex.com/documentation

**Comment by xmedeko** [comment]
Just a new QuickConverter home: https://github.com/JohannesMoersch/QuickConverter

**Comment by lostmsu** [comment]
@Alex141 , QuickConverter documentation is lacking :(
