### ISSUE TITLE
Automated Test Cases

### ISSUE THREAD

**Issue by mnuzzolilo** [Alex141/CalcBinding#34]
I think this library would do well with having automated test cases. The parser seems to not be perfect right now, (see https://github.com/Alex141/CalcBinding/issues/33). If I change something, I want to be sure I'm not breaking other functionality.

**Comment by Alex141** [comment]
Hi, thanks for commit, library has unit tests project, so you can run it manually and check if you break other functionality (as I do before each release). Recently I thought about CI service for library, may be you know good free service for that purpose?

**Comment by mnuzzolilo** [comment]
Here is an updated list of CI solutions. What I normally do is run Jenkins on my own server. You can run it locally on your computer too as needed
http://www.yegor256.com/2014/10/05/ten-hosted-continuous-integration-services.html
