### ISSUE TITLE
FallbackValue

### ISSUE THREAD

**Issue by C6H7NO2** [Alex141/CalcBinding#37]
I'm direly missing support for `FallbackValue` (from `BindingBase`), which should be used when the expression can't be compiled/evaluated/throws. Is it feasible to add?

**Comment by Alex141** [comment]
Sure!

**Comment by Alex141** [comment]
#44

**Comment by DenZuck** [comment]
Is FallBackValue present in version 2.5.1 ?

**Comment by Alex141** [comment]
Planned in current iteration

**Comment by Alex141** [comment]
@C6H7NO2,  @DenZuck  FallbackValue is added in version 2.5.2 - https://www.nuget.org/packages/CalcBinding/2.5.2

**Comment by LucaFagan** [comment]
ok! Thanks.
