### ISSUE TITLE
Binding does not get updated after property changes

### ISSUE THREAD

**Issue by maurosampietro** [Alex141/CalcBinding#39]
If i bind to  MySubView.MyOtherProperty the expression is not reevaluated with the correct value of the property when its value changes.

CalcConverter.Convert is not even called. The binding just does not work.
I don't really have time to study the problem and submit a solution so please help me out.

Thank you.

**Comment by Alex141** [comment]
If CalcConverter.Convert is not called, first, ensure that your binding is written correctly.
1.) Check if there are any messages in the Output window from CalcBinding. 
2.) Check standart WPF binding messages. Open "Tools -> OutputWindow -> WPF Trace Settings" window. Set DataBinding on "Warning" and rerun program. Binding, that cannot be translated, verbose information in output.

**Comment by maurosampietro** [comment]
I checked 3 times the binding before writing... after your firm reply i checked a fourth time and found out the model was not raising the property change. :) 

It's ok for you, thank you
