### ISSUE TITLE
Add much more supported static classes

### ISSUE THREAD

**Issue by Alex141** [Alex141/CalcBinding#4]
Math, Colors, enough?

**Comment by Alex141** [comment]
Brushes

**Comment by Alex141** [comment]
There is some problem to right determine, where e.g. Brushes - is a name of static class and where it is a property of viewModel.

I think it would be reasonable to do so: we select the name of the class and property whole, well, for example Brushes.Red. If static class Brushes has a property Red, then we assume that it is a static class, otherwise - parse as a property of something (we do not know what it is, viewmodel eg)

**Comment by xmedeko** [comment]
You can get an idea how to use enum and static classes from [QuickConverter](https://quickconverter.codeplex.com)

**Comment by Alex141** [comment]
Thank you, good hint!

**Comment by Alex141** [comment]
Static classes are supported in version 2.3.0.0
