### ISSUE TITLE
How to escape the equals sign?

### ISSUE THREAD

**Issue by RafaelSalguero** [Alex141/CalcBinding#42]
In XAML the equals sign is an special character on attribute values.

How to write the following expression?

`Visibility ="{c:Binding Value == null}"`

Thanks

**Comment by Alex141** [comment]
Wrap constructor value 'path' in single quotes like this:

<CheckBox Content="Name is null" IsChecked="{c:Binding 'Name==null', Mode=OneWay}" Margin="0,0,0,5"/>
